import React from "react";
import { View, Text, StyleSheet, ScrollView, Pressable } from "react-native";
import { Stack, useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { ArrowLeft } from "lucide-react-native";
import * as Haptics from "expo-haptics";
import Colors from "@/constants/colors";

const EFFECTIVE_DATE = "April 5, 2026";

export default function TermsOfServiceScreen() {
  const insets = useSafeAreaInsets();
  const router = useRouter();

  return (
    <View style={styles.container}>
      <Stack.Screen options={{ headerShown: false }} />
      <View style={[styles.topBar, { paddingTop: insets.top + 8 }]}>
        <Pressable
          onPress={() => {
            void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
            router.back();
          }}
          style={styles.topBarBtn}
          testID="terms-back-btn"
        >
          <ArrowLeft size={22} color={Colors.dark.text} />
        </Pressable>
        <Text style={styles.topBarTitle}>Terms of Service</Text>
        <View style={styles.spacer} />
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={[styles.scrollContent, { paddingBottom: insets.bottom + 40 }]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.lastUpdated}>Last Updated: {EFFECTIVE_DATE}</Text>

        <Text style={styles.sectionTitle}>1. Acceptance of Terms</Text>
        <Text style={styles.body}>
          By accessing or using Decidr ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the App. These Terms constitute a legally binding agreement between you and Decidr Inc. ("we," "us," or "our").
        </Text>

        <Text style={styles.sectionTitle}>2. Eligibility</Text>
        <Text style={styles.body}>
          You must be at least 13 years of age to use this App. If you are under 18, you represent that your parent or legal guardian has reviewed and agreed to these Terms on your behalf. By using the App, you represent and warrant that you meet these eligibility requirements.
        </Text>

        <Text style={styles.sectionTitle}>3. Account Registration</Text>
        <Text style={styles.body}>
          To use certain features of the App, you must create an account. You agree to provide accurate, current, and complete information during registration and to update such information as necessary. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account.
        </Text>

        <Text style={styles.sectionTitle}>4. User Content</Text>
        <Text style={styles.body}>
          You retain ownership of the content you submit to the App, including debate topics, arguments, votes, and comments ("User Content"). By submitting User Content, you grant us a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform your User Content in connection with the App and our business operations.{"\n\n"}You represent and warrant that you own or have the necessary rights to submit your User Content and that your User Content does not violate any third-party rights or applicable laws.
        </Text>

        <Text style={styles.sectionTitle}>5. Prohibited Conduct</Text>
        <Text style={styles.body}>
          You agree not to:{"\n\n"}• Post content that is unlawful, defamatory, obscene, threatening, harassing, or hateful{"\n"}• Impersonate any person or entity{"\n"}• Manipulate votes or engage in fraudulent activity{"\n"}• Use bots, scripts, or automated tools to interact with the App{"\n"}• Attempt to circumvent security features{"\n"}• Interfere with or disrupt the App's infrastructure{"\n"}• Upload malware, viruses, or other harmful content{"\n"}• Collect or harvest personal data from other users{"\n"}• Use the App for any commercial purpose without our written consent
        </Text>

        <Text style={styles.sectionTitle}>6. AI Judge Feature</Text>
        <Text style={styles.body}>
          The App includes an AI-powered judgment feature ("AI Judge") that analyzes debate topics and provides a verdict. The AI Judge's opinions are generated by artificial intelligence and are provided for entertainment and informational purposes only. They do not constitute professional advice and should not be relied upon as the sole basis for any decision. We make no representations or warranties regarding the accuracy, completeness, or reliability of AI-generated content.
        </Text>

        <Text style={styles.sectionTitle}>7. Intellectual Property</Text>
        <Text style={styles.body}>
          The App and its original content (excluding User Content), features, and functionality are and will remain the exclusive property of Decidr Inc. and its licensors. The App is protected by copyright, trademark, and other laws. Our trademarks and trade dress may not be used without our prior written consent.
        </Text>

        <Text style={styles.sectionTitle}>8. Termination</Text>
        <Text style={styles.body}>
          We may terminate or suspend your account and access to the App immediately, without prior notice or liability, for any reason, including breach of these Terms. Upon termination, your right to use the App will immediately cease. All provisions of the Terms which by their nature should survive termination shall survive.
        </Text>

        <Text style={styles.sectionTitle}>9. Disclaimers</Text>
        <Text style={styles.body}>
          THE APP IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.
        </Text>

        <Text style={styles.sectionTitle}>10. Limitation of Liability</Text>
        <Text style={styles.body}>
          IN NO EVENT SHALL DECIDR INC., ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR RELATED TO YOUR USE OF THE APP. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
        </Text>

        <Text style={styles.sectionTitle}>11. Governing Law</Text>
        <Text style={styles.body}>
          These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved exclusively in the state or federal courts located in Delaware.
        </Text>

        <Text style={styles.sectionTitle}>12. Changes to Terms</Text>
        <Text style={styles.body}>
          We reserve the right to modify these Terms at any time. We will notify you of material changes by posting the updated Terms within the App and updating the "Last Updated" date. Your continued use of the App after such changes constitutes your acceptance of the revised Terms.
        </Text>

        <Text style={styles.sectionTitle}>13. Contact Us</Text>
        <Text style={styles.body}>
          If you have questions about these Terms, please contact us at:{"\n\n"}Email: legal@decidr.app{"\n"}Address: Decidr Inc., 123 Innovation Drive, Wilmington, DE 19801
        </Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.dark.background,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: Colors.dark.background,
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.dark.border,
    gap: 12,
  },
  topBarBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.dark.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  topBarTitle: {
    flex: 1,
    color: Colors.dark.text,
    fontSize: 16,
    fontWeight: "700" as const,
    textAlign: "center",
  },
  spacer: {
    width: 36,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
  },
  lastUpdated: {
    fontSize: 13,
    color: Colors.dark.textTertiary,
    marginBottom: 24,
    fontWeight: "500" as const,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700" as const,
    color: Colors.dark.text,
    marginTop: 24,
    marginBottom: 10,
  },
  body: {
    fontSize: 14,
    color: Colors.dark.textSecondary,
    lineHeight: 22,
  },
});

